# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0002_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='status',
            field=models.IntegerField(choices=[(0, 'study is ready'), (1, 'study is running'), (2, 'study is finished')], default=0),
        ),
    ]
