# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_study_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='client_ip',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='study',
            name='client_port',
            field=models.IntegerField(default=0),
        ),
    ]
