# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trail_pb2 as trail__pb2


class TrailStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunTrail = channel.unary_unary(
        '/Trail/RunTrail',
        request_serializer=trail__pb2.Data.SerializeToString,
        response_deserializer=trail__pb2.ReplyMessage.FromString,
        )


class TrailServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunTrail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrailServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunTrail': grpc.unary_unary_rpc_method_handler(
          servicer.RunTrail,
          request_deserializer=trail__pb2.Data.FromString,
          response_serializer=trail__pb2.ReplyMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Trail', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
