# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trail.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0btrail.proto\"&\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08trail_id\x18\x02 \x01(\x05\"\x1f\n\x0cReplyMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2)\n\x05Trail\x12 \n\x08RunTrail\x12\x05.Data\x1a\r.ReplyMessageb\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Data.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trail_id', full_name='Data.trail_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=53,
)


_REPLYMESSAGE = _descriptor.Descriptor(
  name='ReplyMessage',
  full_name='ReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ReplyMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['ReplyMessage'] = _REPLYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'trail_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  ))
_sym_db.RegisterMessage(Data)

ReplyMessage = _reflection.GeneratedProtocolMessageType('ReplyMessage', (_message.Message,), dict(
  DESCRIPTOR = _REPLYMESSAGE,
  __module__ = 'trail_pb2'
  # @@protoc_insertion_point(class_scope:ReplyMessage)
  ))
_sym_db.RegisterMessage(ReplyMessage)



_TRAIL = _descriptor.ServiceDescriptor(
  name='Trail',
  full_name='Trail',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=88,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunTrail',
    full_name='Trail.RunTrail',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_REPLYMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAIL)

DESCRIPTOR.services_by_name['Trail'] = _TRAIL

# @@protoc_insertion_point(module_scope)
